Umb.LL_VPR/Controllers/AuthSurfaceController.cs
using System;
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using Umb.VPR.ViewModels;

namespace Umb.VPR.Controllers
{
    public class AuthSurfaceController : SurfaceController
    {
        #region Controller Methods

        [HttpGet]
        [ActionName("RenderLogin")]
        public ActionResult RenderLogin()
        {
            var model = new LoginViewModel
            {
                ReturnUrl = (CurrentPage.Url != Request.Url.PathAndQuery) ?
                    Request.Url.PathAndQuery :
                    Umbraco.NiceUrl(Convert.ToInt32(CurrentPage.GetProperty("loginSuccessPage").Value))
            };

            return PartialView("VPRForms/_login", model);
        }

        [HttpPost]
        [ActionName("HandleLogin")]
        [ValidateAntiForgeryToken]
        public ActionResult HandleLogin(LoginViewModel model)
        {
            // Check if user is already logged in 
            if (Members.IsLoggedIn())
                Redirect(model.ReturnUrl);

            // Check if form data is valid.
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            // Attempt to Login
            if (Membership.ValidateUser(model.Username, model.Password))
            {
                FormsAuthentication.SetAuthCookie(model.Username, false);
                return Redirect(model.ReturnUrl);
            }
            else
            {
                // Login failed, 
                TempData.Add("LoginFailure", "Login failed, please try again.");
                return RedirectToCurrentUmbracoPage();
            }
        }
        
        [HttpGet]
        [ActionName("RenderRegister")]
        public ActionResult RenderRegister()
        {
            var model = new RegisterViewModel
            {
                ReturnUrl = (CurrentPage.Url != Request.Url.PathAndQuery) ?
                    Request.Url.PathAndQuery : 
                    Umbraco.NiceUrl(Convert.ToInt32(CurrentPage.GetProperty("registerSuccessPage").Value))
            };

            return PartialView("VPRForms/_register", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult HandleRegister(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            // Model is valid, so let's try to create the member.
            var tempGUID = Guid.NewGuid().ToString();
            try
            {
                // Attempt to create and initialize the new member.
                IMember newMember = Services.MemberService.CreateMember(model.Email, model.Email, GetDisplayName(model.FirstName, model.LastName), "Customer");
                newMember.IsApproved = false;
                newMember.SetValue("firstName", model.FirstName);
                newMember.SetValue("lastName", model.LastName);
                newMember.SetValue("companyName", model.Company);
                newMember.SetValue("jobPosition", model.Position);
                newMember.SetValue("hasVerifiedEmail", false);
                newMember.SetValue("joinedDate", DateTime.Now);
                newMember.SetValue("emailVerifyGUID", tempGUID);

                // Persist new member to the database and set roles and password.
                Services.MemberService.Save(newMember);
                Services.MemberService.AssignRole(newMember.Id, "VPR");
                Services.MemberService.SavePassword(newMember, model.Password);
            }
            catch (Exception ex)
            {
                TempData["RegistrationFailed"] = ex.Message;
                //ModelState.AddModelError("", ex.Message);
                return CurrentUmbracoPage();
            }

            // Send Email verification email.
            //var emailFrom = GlobalSettings.GetPropertyValue<string>("websiteEmailAddress");
            //var mailHelper = new EmailHelper(SmtpHost, SmtpUsername, SmtpPassword);
            //mailHelper.SendVerifyEmail(model.Email, emailFrom, tempGUID);

            // Update success flag (in a TempData key)
            //TempData["IsSuccessful"] = true;
            return RedirectToCurrentUmbracoPage();
        }

        [HttpGet]
        [ActionName("RenderForgotPassword")]
        public ActionResult RenderForgotPassword()
        {
            return PartialView("VPRForms/_forgotPassword", new ForgotPasswordViewModel());
        }

        [HttpPost]
        [ActionName("HandleForgotPassword")]
        [ValidateAntiForgeryToken]
        public ActionResult HandleForgotPassword(ForgotPasswordViewModel model)
        {
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            // Find the member with the matching email address.
            var member = Services.MemberService.GetByEmail(model.EmailAddress);
            if (member != null)
            {
                // We found the member matching the email.
                // Initialize expiry timout (15 minutes).
                var expiryTime = DateTime.Now.AddMinutes(15);

                // Update member expiry guid.
                var resetGuid = expiryTime.ToString("ddMMyyyyHHmmssFFFF");
                member.SetValue("resetGUID", resetGuid);
                Services.MemberService.Save(member);

                // Send the member an email with a Password Reset GUID in it.
                //var emailFrom = "bruce@syncrony.com";
                //var emailHelper = new EmailHelper();
                //emailHelper.SendResetPasswordEmail(member.Email, emailFrom, resetGuid);
            }
            else
            {
                ModelState.AddModelError("", $"We could not find a customer account matching {model.EmailAddress}");
                return CurrentUmbracoPage();
            }

            return RedirectToCurrentUmbracoPage();
        }

        [HttpGet]
        [ActionName("RenderResetPassword")]
        public ActionResult RenderResetPassword()
        {
            return PartialView("LLForms/_resetPassword", new ResetPasswordViewModel());
        }

        [HttpPost]
        [ActionName("HandleResetPassword")]
        [ValidateAntiForgeryToken]
        public ActionResult HandleResetPassword(ResetPasswordViewModel model)
        {
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            // Find the member with the matching email address.
            var member = Services.MemberService.GetByEmail(model.EmailAddress);
            if (member != null)
            {
                // Get the querystring GUID
                var resetQS = Request.QueryString["resetGUID"];
                if (!string.IsNullOrEmpty(resetQS))
                {
                    // See if the QS matches the value on the member property
                    if (member.GetValue<string>("resetGUID") == resetQS)
                    {
                        // Got a match, now check to see if the exiry window is valid.
                        DateTime currentTime = DateTime.Now;
                        DateTime expiryTime = DateTime.ParseExact(resetQS, "ddMMyyyyHHmmssFFFF", null);
                        if (currentTime.CompareTo(expiryTime) < 0)
                        {
                            // Not expired, so update user password and remove the reset guid.
                            member.RawPasswordValue = model.Password;
                            member.SetValue("resetGUID", string.Empty);
                            Services.MemberService.Save(member);
                            Redirect("/member-login");
                        }
                        else
                        {
                            //ERROR: Reset GUID has expired
                            ModelState.AddModelError("", "Password Reset GUID has expired");
                            return CurrentUmbracoPage();
                        }
                    }
                    else
                    {
                        // ERROR: QS does not match what is stored on member property
                        ModelState.AddModelError("", "Invalid Password Reset GUID");
                        return CurrentUmbracoPage();
                    }
                }
                else
                {
                    // ERROR: No QS present - Invalid resetGUID
                    ModelState.AddModelError("", "Invalid Password Reset GUID");
                    return CurrentUmbracoPage();
                }
            }

            return RedirectToCurrentUmbracoPage();
        }

        #endregion

        #region Helper Methods

        private string GetDisplayName(string firstName, string lastName)
        {
            return $"{firstName} {lastName}";
        }

        #endregion
    }
}

Umb.LL_VPR/Views/Company.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage<ContentModels.Company>
@using ContentModels = Umbraco.Web.PublishedContentModels;
@{
	Layout = null;
}

Umb.LL_VPR/Views/RegisterPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Umb.VPR.Controllers
@{
    Layout = "USNMaster.cshtml";
}

@Html.Partial("USNMiscPageElements/USN_HeaderImageSection", @Model.Content)

<!-- CONTENT -->
<section class="content">
    <!-- CONTAINER -->
    <div class="container">
	    <!-- ROW -->
	    <div class="row">
		    <!-- CONTENT COL -->
		    <div @Html.Partial("USNLayout/USN_ContentColumnStyle",@Model.Content)>
			    @Html.Partial("USNMiscPageElements/USN_StandardPageTitle", @Model.Content)
			    <!-- IMAGE -->
			    @Html.Partial("USNMiscPageElements/USN_MainImage",@Model.Content)
			    <!--// IMAGE -->
			    @Umbraco.Field("bodyText")
                <!-- FORM -->
                @Html.Action("RenderRegister", "AuthSurface")
			    <!--// FORM -->				
		    </div>
		    <!--// CONTENT COL -->			
		    @Html.Partial("USNLayout/USN_PodAndNavColumn", @Model.Content)		
	    </div>
	    <!--// ROW -->
    </div>
    <!--// CONTAINER -->
</section>	
<!--// CONTENT -->

@Html.Partial("USNSiteWidePods/USN_SitewidePods", @Model.Content, new ViewDataDictionary { { "podstyle", "horizontal" } })
@section BodyTag{@Html.Raw(" class=\"standard-page\"")}

Umb.LL_VPR/Views/USNAdvancedPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "USNMaster.cshtml";
}

@Html.Partial("USNAdvancedPageComponents/USN_AdvancedPageComponents", @Model.Content)	
	
@section BodyTag
{
    @Html.Raw(" class=\"advanced-page\"")
}

Umb.LL_VPR/Views/USNAdvancedPageBlogPost.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "USNMaster.cshtml";
}

@Html.Partial("USNAdvancedPageComponents/USN_AdvancedPageComponents", @Model.Content)	


<!-- CONTENT -->
<section class="content apc standard-components">
    <div class="container">

        <!-- ROW -->
        <div class="row">

            <!-- MID COL -->
            <div id="mid-col" class="col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12">

                <!-- META -->
                @Html.Partial("USNBlog/USN_BlogMeta", @Model.Content)
                <!--// META -->
                <!-- AUTHOR BIO -->
                @Html.Partial("USNBlog/USN_BlogAuthorship", @Model.Content)
                <!--// AUTHOR BIO -->
                <!-- PAGINATION  -->
                @Html.Partial("USNBlog/USN_BlogPostPreviousNext", @Model.Content)
                <!--// PAGINATION -->
                <!-- COMMENTS -->
                @Html.Partial("USNBlog/USN_BlogComments", @Model.Content)
                <!--// COMMENTS -->

            </div>
            <!--// MID COL -->

        </div>
        <!--// ROW -->

    </div>
</section>
<!--// CONTENT -->
	
@section BodyTag
{
    @Html.Raw(" class=\"advanced-page\"")
}

Umb.LL_VPR/Views/USNBlogLandingPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "USNMaster.cshtml";
}

@Html.Partial("USNMiscPageElements/USN_HeaderImageSection", @Model.Content)

<!-- CONTENT -->
<section class="content">

    <!-- CONTAINER -->
    <div class="container">
	    
        <!-- ROW -->
	    <div class="row">
			
		    <!-- CONTENT COL -->
		    <div @Html.Partial("USNLayout/USN_ContentColumnStyle",@Model.Content)>
				
			    @Html.Partial("USNBlog/USN_BlogListing",@Model.Content)
				
		    </div>
		    <!--// CONTENT COL -->

		    @Html.Partial("USNLayout/USN_PodAndNavColumn", @Model.Content)
		
	    </div>
	    <!--// ROW -->
		
    </div>
    <!--// CONTAINER -->

</section>	
<!--// CONTENT -->

@Html.Partial("USNSiteWidePods/USN_SitewidePods", @Model.Content, new ViewDataDictionary { { "podstyle", "horizontal" } })

@section BodyTag{@Html.Raw(" class=\"standard-page\"")}

@section FooterScripts
{
    @Html.Partial("USNBlog/USN_BlogDisqusCommentCountScript", @Model.Content)
}

Umb.LL_VPR/Views/USNBlogRSS.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}@Html.Partial("USNBlog/USN_BlogRSS",@Model.Content)

Umb.LL_VPR/Views/USNHomeRedirect.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

@{
    IEnumerable<IPublishedContent> rootNode = Umbraco.TypedContentAtRoot();
    var home = rootNode.Where(x => x.IsDocumentType("USNHomepage")).First();
	
	Response.Redirect(home.Url);
}

Umb.LL_VPR/Views/USNLoginPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@using Umb.VPR.Controllers
@{
    Layout = "USNMaster.cshtml";

    if (!String.IsNullOrEmpty(Request.QueryString["signout"]))
    {
        FormsAuthentication.SignOut();
        Context.Response.Redirect(Model.Content.Url, true);
    }
}

@Html.Partial("USNMiscPageElements/USN_HeaderImageSection", @Model.Content)

<!-- CONTENT -->
<section class="content">

    <!-- CONTAINER -->
    <div class="container">
	
	    <!-- ROW -->
	    <div class="row">
			
		    <!-- CONTENT COL -->
		    <div @Html.Partial("USNLayout/USN_ContentColumnStyle",@Model.Content)>
				
			    @Html.Partial("USNMiscPageElements/USN_StandardPageTitle", @Model.Content)
		
			    <!-- IMAGE -->
			    @Html.Partial("USNMiscPageElements/USN_MainImage",@Model.Content)
			    <!--// IMAGE -->
	       
			    @Umbraco.Field("bodyText")

                <!-- FORM -->
                @Html.Action("RenderLogin", "AuthSurface")
			    <!--// FORM -->
				
		    </div>
		    <!--// CONTENT COL -->
			
		    @Html.Partial("USNLayout/USN_PodAndNavColumn", @Model.Content)
		
	    </div>
	    <!--// ROW -->

    </div>
    <!--// CONTAINER -->

</section>	
<!--// CONTENT -->

@Html.Partial("USNSiteWidePods/USN_SitewidePods", @Model.Content, new ViewDataDictionary { { "podstyle", "horizontal" } })

@section BodyTag{@Html.Raw(" class=\"standard-page\"")}

Umb.LL_VPR/Views/USNMaster.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}
<!DOCTYPE html>
<!--[if lt IE 7 ]> <html lang="en" class="no-js ie6"> <![endif]-->
<!--[if IE 7 ]>    <html lang="en" class="no-js ie7"> <![endif]-->
<!--[if IE 8 ]>    <html lang="en" class="no-js ie8"> <![endif]-->
<!--[if IE 9 ]>    <html lang="en" class="no-js ie9"> <![endif]-->
<!--[if (gt IE 9)|!(IE)]><!-->
<html lang="en" class="no-js">
<!--<![endif]-->
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=0">
    <meta name="description" content='@Umbraco.Field("metaDescription")'>
    @Html.Partial("USNWebsiteHeadSection/USN_SEOPageHead", @Model.Content)

    <!-- WEB FONT -->
    <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css" rel="stylesheet">
    <link href="//code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css" rel="stylesheet">

    <!-- STYLESHEETS -->
    <link rel="stylesheet" href="/css/bootstrap.css">
    <link rel="stylesheet" href="/css/base.css">
    <link rel="stylesheet" href="/css/plugins.css">
    <link rel="stylesheet" href="/css/palette.css">
    <link rel="stylesheet" href="/css/layout.css">
	
    <!-- INTERNAL STYLES -->
    @Html.Partial("USNWebsiteHeadSection/USN_InternalStyles", @Model.Content)

    <!-- SCRIPTS -->
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.js"></script>
    <script src="/scripts/bootstrap.js"></script>
    <script src="/scripts/plugins.js"></script>
    <script src="/scripts/application.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-validate/1.15.0/jquery.validate.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery-validation-unobtrusive/3.2.6/jquery.validate.unobtrusive.min.js"></script>
    <script src="/scripts/jquery.unobtrusive-ajax.min.js"></script>

	<!--[if IE]>
	<link rel="stylesheet" href="/css/ie.css">
	<![endif]-->

	
    <!--[if lt IE 9]>
    <script src="//oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="//oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->

    <!-- ICONS -->
    @Html.Partial("USNWebsiteHeadSection/USN_Icons", @Model.Content)

    @RenderSection("Head", false)

    @Html.Partial("USNWebsiteHeadSection/USN_HeaderScripts", @Model.Content)

</head>
<body @RenderSection("BodyTag", false)>

    <!-- SITE -->
    <div id="site">

        <!-- HEADER -->
        <header>
            <div class="container">

                <div class="row">

                    <!-- LOGO -->
                    @Html.Partial("USNWebsiteHeadSection/USN_WebsiteLogo", @Model.Content)
                    <!--// LOGO -->
                    <!-- EXPAND -->
                    <a class="expand">
                        <em>Menu</em>
                        <span class="line top"></span>
                        <span class="line mid"></span>
                        <span class="line bottom"></span>
                    </a>
                    <!--// EXPAND -->
                    <!-- NAVIGATION -->
                    <div class="navigation">

                        <!-- REVEAL -->
                        <div class="reveal">

                            @Html.Partial("USNNavigation/USN_MainNavigation", @Model.Content)

                            @Html.Partial("USNForms/USN_SearchForm", @Model.Content)

                            @Html.Partial("USNNavigation/USN_TopNavigation", @Model.Content)

                        </div>
                        <!--// REVEAL -->
                    </div>
                    <!--// NAVIGATION -->
                </div>

            </div>
        </header>
        <!--// HEADER -->
        @RenderBody()

        <!-- OUTRO STRIP -->
        @Html.Partial("USNMiscPageElements/USN_OutroStripSection", @Model.Content)
        <!--// OUTRO STRIP -->
        <!-- BREADCRUMB -->
        @Html.Partial("USNNavigation/USN_Breadcrumb", @Model.Content)
        <!--// BREADCRUMB -->
        <!-- FOOTER -->
        <footer class="c4-bg">
            <div class="container">

                <!-- ROW -->
                <div class="row">

                    <div class="col-md-4 col-xs-12">

                        <!-- COMPANY DETAILS -->
                        @Html.Partial("USNWebsiteFooterSection/USN_FooterContactInformation", @Model.Content)
                        <!--// COMPANY DETAILS -->

                    </div>

                    <div class="col-md-4 col-xs-12">

                        @Html.Partial("USNNavigation/USN_FooterQuickLinks", @Model.Content)

                    </div>

                    <div class="col-md-3 col-md-offset-1 col-xs-12">

                        @Html.Partial("USNWebsiteFooterSection/USN_FooterSocialLinks", @Model.Content)

                    </div>

                </div>
                <!--// ROW -->
                <!-- ROW -->
                <div class="row">

                    <div class="col-sm-12">

                        <nav class="footer">
                            <ul class="nav">
                                <li class="copyright"><div>&copy; @DateTime.Now.ToString("yyyy")</div></li>
                                @Html.Partial("USNNavigation/USN_FooterNavigation", @Model.Content)
                                <li class="site_credit pull-right">
                                    <div>a premium Umbraco theme from</div>
                                    <a target="_blank" title="Link will open in a new window/tab" href="http://www.uskinned.net"><span>uSkinned&trade;</span></a>
                                </li>
                            </ul>
                        </nav>

                    </div>

                </div>
                <!--// ROW -->

            </div>
        </footer>
        <!--// FOOTER -->
        <!-- BACK TO TOP -->
        <span id="top-link-block" class="c1-bg c5-text">
            <a href="#top" class="c1-bg c5-text" onclick="$('html,body').animate({scrollTop:0},'slow');return false;">
                <i class="ion-chevron-up"></i>
            </a>
        </span>
        <!--// BACK TO TOP -->

    </div>
    <!--// SITE -->
    @RenderSection("FooterScripts", false)
    @Html.Partial("USNWebsiteFooterSection/USN_FooterScripts", @Model.Content)
</body>
</html>

Umb.LL_VPR/Views/USNParentRedirect.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = null;
}

@{
    var parent = Model.Content.Parent;
	
	Response.Redirect(parent.Url);
}

Umb.LL_VPR/Views/USNSearchResultsPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "USNMaster.cshtml";
}

@Html.Partial("USNMiscPageElements/USN_HeaderImageSection", @Model.Content)

<!-- CONTENT -->
<section class="content">

    <!-- CONTAINER -->
    <div class="container">
				
	    <!-- ROW -->
	    <div class="row">
			
		    <!-- CONTENT COL -->
		    <div @Html.Partial("USNLayout/USN_ContentColumnStyle",@Model.Content)>
				
			    @Html.Partial("USNMiscPageElements/USN_StandardPageTitle", @Model.Content)
		
			    <!-- IMAGE -->
			    @Html.Partial("USNMiscPageElements/USN_MainImage",@Model.Content)
			    <!--// IMAGE -->
	       
			    @Umbraco.Field("bodyText")
		
			    @Html.Partial("USNListings/USN_SearchResults",@Model.Content)
				
		    </div>
		    <!--// CONTENT COL -->
			
		    @Html.Partial("USNLayout/USN_PodAndNavColumn", @Model.Content)
				
	    </div>
	    <!--// ROW -->

    </div>
    <!--// CONTAINER -->

</section>	
<!--// CONTENT -->

@Html.Partial("USNSiteWidePods/USN_SitewidePods", @Model.Content, new ViewDataDictionary { { "podstyle", "horizontal" } })
		
@section BodyTag{@Html.Raw(" class=\"standard-page\"")}

Umb.LL_VPR/Views/USNSitemapPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "USNMaster.cshtml";

    if (CurrentPage.Name == "Page not found")
    {
        Response.Status = "404 Not Found";
        Response.StatusCode = 404;
    }
}

@Html.Partial("USNMiscPageElements/USN_HeaderImageSection", @Model.Content)

<!-- CONTENT -->
<section class="content">

    <!-- CONTAINER -->
    <div class="container">
		
	    <!-- ROW -->
	    <div class="row">
			
		    <!-- CONTENT COL -->
		    <div @Html.Partial("USNLayout/USN_ContentColumnStyle",@Model.Content)>
				
                @Html.Partial("USNMiscPageElements/USN_StandardPageTitle", @Model.Content)
		
			    <!-- IMAGE -->
			    @Html.Partial("USNMiscPageElements/USN_MainImage",@Model.Content)
			    <!--// IMAGE -->
	       
			    @Umbraco.Field("bodyText")
		
			    @Html.Partial("USNNavigation/USN_Sitemap",@Model.Content)
				
		    </div>
		    <!--// CONTENT COL -->
			
		    @Html.Partial("USNLayout/USN_PodAndNavColumn", @Model.Content)
						
	    </div>
	    <!--// ROW -->

    </div>
    <!--// CONTAINER -->

</section>	
<!--// CONTENT -->

@Html.Partial("USNSiteWidePods/USN_SitewidePods", @Model.Content, new ViewDataDictionary { { "podstyle", "horizontal" } })
		
@section BodyTag{@Html.Raw(" class=\"standard-page\"")}

Umb.LL_VPR/Views/USNStandardPage.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "USNMaster.cshtml";
}

@Html.Partial("USNMiscPageElements/USN_HeaderImageSection", @Model.Content)

<!-- CONTENT -->
<section class="content">

    <!-- CONTAINER -->
    <div class="container">

        <!-- ROW -->
        <div class="row">

            <!-- CONTENT COL -->
            <div @Html.Partial("USNLayout/USN_ContentColumnStyle", @Model.Content)>

                @Html.Partial("USNMiscPageElements/USN_StandardPageTitle", @Model.Content)

                <!-- IMAGE -->
                @Html.Partial("USNMiscPageElements/USN_MainImage", @Model.Content)
                <!--// IMAGE -->

                @Umbraco.Field("bodyText")

                @Html.Partial("USNListings/USN_SubpageListing", @Model.Content)

                @Html.Partial("USNStandardPageComponents/USN_StandardPageComponents", @Model.Content)

            </div>
            <!--// CONTENT COL -->

            @Html.Partial("USNLayout/USN_PodAndNavColumn", @Model.Content)

        </div>
        <!--// ROW -->
    
    </div>
    <!--// CONTAINER -->

</section>
<!--// CONTENT -->

@Html.Partial("USNSiteWidePods/USN_SitewidePods", @Model.Content, new ViewDataDictionary { { "podstyle", "horizontal" } })

@section BodyTag{@Html.Raw(" class=\"standard-page\"")}

Umb.LL_VPR/Views/USNStandardPageBlogPost.cshtml
@inherits Umbraco.Web.Mvc.UmbracoTemplatePage
@{
    Layout = "USNMaster.cshtml";
}

@Html.Partial("USNMiscPageElements/USN_HeaderImageSection", @Model.Content)

<!-- CONTENT -->
<section class="content">

    <!-- CONTAINER -->
    <div class="container">
		
	    <!-- ROW -->
	    <div class="row">
			
		    <!-- CONTENT COL -->
		    <div @Html.Partial("USNLayout/USN_ContentColumnStyle",@Model.Content)>
				
                @Html.Partial("USNMiscPageElements/USN_StandardPageTitle", @Model.Content)
		    
			    <!-- IMAGE -->
			    @Html.Partial("USNMiscPageElements/USN_MainImage",@Model.Content)
			    <!--// IMAGE -->
	       
			    @Umbraco.Field("bodyText")
		
				
			    @Html.Partial("USNStandardPageComponents/USN_StandardPageComponents",@Model.Content)
		
                <!-- META -->
                @Html.Partial("USNBlog/USN_BlogMeta", @Model.Content)
                <!--// META -->

			    <!-- AUTHOR BIO -->
			    @Html.Partial("USNBlog/USN_BlogAuthorship",@Model.Content)
			    <!--// AUTHOR BIO -->
		
                <!-- PAGINATION  -->
			    @Html.Partial("USNBlog/USN_BlogPostPreviousNext",@Model.Content)	
		        <!--// PAGINATION -->

                <!-- COMMENTS -->
			    @Html.Partial("USNBlog/USN_BlogComments",@Model.Content)
                <!--// COMMENTS -->
		    </div>
		    <!--// CONTENT COL -->
			
		    @Html.Partial("USNLayout/USN_PodAndNavColumn", @Model.Content)
			
	    </div>
	    <!--// ROW -->

    </div>
    <!--// CONTAINER -->

</section>	
<!--// CONTENT -->

@Html.Partial("USNSiteWidePods/USN_SitewidePods", @Model.Content, new ViewDataDictionary { { "podstyle", "horizontal" } })
		
@section BodyTag{@Html.Raw(" class=\"standard-page\"")}

@section FooterScripts
{
    @Html.Partial("USNBlog/USN_BlogDisqusCommentCountScript", @Model.Content)
}