Umb.LL_VPR/ViewModels/ForgotPasswordViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Umb.VPR.ViewModels
{
    public class ForgotPasswordViewModel
    {
        [DisplayName("Email address")]
        [Required(ErrorMessage = "Please enter your email address")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address.")]
        public string EmailAddress { get; set; }

        public int CurrentNodeID { get; set; }
    }
}

Umb.LL_VPR/ViewModels/LoginViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Umb.VPR.ViewModels
{
    public class LoginViewModel
    {
        [Display(Name = "Email Address")]
        [Required]
        public string Username { get; set; }

        [Required]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        public string ReturnUrl { get; set; }
    }
}

Umb.LL_VPR/ViewModels/RegisterViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Umb.VPR.ViewModels
{
    public class RegisterViewModel
    {
        #region Ctor

        public RegisterViewModel()
        {

        }

        #endregion

        #region Properties

        [Required(ErrorMessage = "Please enter your first name.")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Please enter a value between 2 - 50 characters long")]
        [Display(Name = "First Name", Order = 1)]
        public string FirstName { get; set; }

        [Required(ErrorMessage = "Please enter your last name")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Please enter a value between 2 - 50 characters long")]
        [Display(Name = "Last Name", Order = 2)]
        public string LastName { get; set; }

        [Required(ErrorMessage = "Please enter your company")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Please enter a value between 2 - 50 characters long")]
        [Display(Order = 3)]
        public string Company { get; set; }

        [Required(ErrorMessage = "Please enter your position")]
        [StringLength(50, MinimumLength = 2, ErrorMessage = "Please enter a value between 2 - 50 characters long")]
        [Display(Order = 4)]
        public string Position { get; set; }

        [Display(Name = "Email Address")]
        [Required(ErrorMessage = "Please enter an email address")]
        [EmailAddress(ErrorMessage = "Please enter a valid email address")]
        [DataType(DataType.EmailAddress)]
        [System.Web.Mvc.Remote("CheckUserExists", "AuthSurface")]
        public string Email { get; set; }

        [Required(ErrorMessage = "Please enter a password")]
        [StringLength(14, MinimumLength = 6, ErrorMessage = "Please enter a password between 6 - 14 characters long")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Required(ErrorMessage = "Please enter you password confirmation")]
        [Display(Name = "Confirm Password")]
        [DataType(DataType.Password)]
        [Compare("Password", ErrorMessage = "Confirm password doesn't match, Please try again !")]
        public string ConfirmPassword { get; set; }
        
        public string ReturnUrl { get; set; }

        #endregion
    }
}

Umb.LL_VPR/Controllers/AuthSurfaceController.cs
using System;
using System.Web.Mvc;
using System.Web.Security;
using Umbraco.Core.Models;
using Umbraco.Web.Mvc;
using Umb.VPR.ViewModels;

namespace Umb.VPR.Controllers
{
    public class AuthSurfaceController : SurfaceController
    {
        #region Controller Methods

        [HttpGet]
        [ActionName("RenderLogin")]
        public ActionResult RenderLogin()
        {
            var model = new LoginViewModel
            {
                ReturnUrl = (CurrentPage.Url != Request.Url.PathAndQuery) ?
                    Request.Url.PathAndQuery :
                    Umbraco.NiceUrl(Convert.ToInt32(CurrentPage.GetProperty("loginSuccessPage").Value))
            };

            return PartialView("VPRForms/_login", model);
        }

        [HttpPost]
        [ActionName("HandleLogin")]
        [ValidateAntiForgeryToken]
        public ActionResult HandleLogin(LoginViewModel model)
        {
            // Check if user is already logged in 
            if (Members.IsLoggedIn())
                Redirect(model.ReturnUrl);

            // Check if form data is valid.
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            // Attempt to Login
            if (Membership.ValidateUser(model.Username, model.Password))
            {
                FormsAuthentication.SetAuthCookie(model.Username, false);
                return Redirect(model.ReturnUrl);
            }
            else
            {
                // Login failed, 
                TempData.Add("LoginFailure", "Login failed, please try again.");
                return RedirectToCurrentUmbracoPage();
            }
        }
        
        [HttpGet]
        [ActionName("RenderRegister")]
        public ActionResult RenderRegister()
        {
            var model = new RegisterViewModel
            {
                ReturnUrl = (CurrentPage.Url != Request.Url.PathAndQuery) ?
                    Request.Url.PathAndQuery : 
                    Umbraco.NiceUrl(Convert.ToInt32(CurrentPage.GetProperty("registerSuccessPage").Value))
            };

            return PartialView("VPRForms/_register", model);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult HandleRegister(RegisterViewModel model)
        {
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            // Model is valid, so let's try to create the member.
            var tempGUID = Guid.NewGuid().ToString();
            try
            {
                // Attempt to create and initialize the new member.
                IMember newMember = Services.MemberService.CreateMember(model.Email, model.Email, GetDisplayName(model.FirstName, model.LastName), "Customer");
                newMember.IsApproved = false;
                newMember.SetValue("firstName", model.FirstName);
                newMember.SetValue("lastName", model.LastName);
                newMember.SetValue("companyName", model.Company);
                newMember.SetValue("jobPosition", model.Position);
                newMember.SetValue("hasVerifiedEmail", false);
                newMember.SetValue("joinedDate", DateTime.Now);
                newMember.SetValue("emailVerifyGUID", tempGUID);

                // Persist new member to the database and set roles and password.
                Services.MemberService.Save(newMember);
                Services.MemberService.AssignRole(newMember.Id, "VPR");
                Services.MemberService.SavePassword(newMember, model.Password);
            }
            catch (Exception ex)
            {
                TempData["RegistrationFailed"] = ex.Message;
                //ModelState.AddModelError("", ex.Message);
                return CurrentUmbracoPage();
            }

            // Send Email verification email.
            //var emailFrom = GlobalSettings.GetPropertyValue<string>("websiteEmailAddress");
            //var mailHelper = new EmailHelper(SmtpHost, SmtpUsername, SmtpPassword);
            //mailHelper.SendVerifyEmail(model.Email, emailFrom, tempGUID);

            // Update success flag (in a TempData key)
            //TempData["IsSuccessful"] = true;
            return RedirectToCurrentUmbracoPage();
        }

        [HttpGet]
        [ActionName("RenderForgotPassword")]
        public ActionResult RenderForgotPassword()
        {
            return PartialView("VPRForms/_forgotPassword", new ForgotPasswordViewModel());
        }

        [HttpPost]
        [ActionName("HandleForgotPassword")]
        [ValidateAntiForgeryToken]
        public ActionResult HandleForgotPassword(ForgotPasswordViewModel model)
        {
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            // Find the member with the matching email address.
            var member = Services.MemberService.GetByEmail(model.EmailAddress);
            if (member != null)
            {
                // We found the member matching the email.
                // Initialize expiry timout (15 minutes).
                var expiryTime = DateTime.Now.AddMinutes(15);

                // Update member expiry guid.
                var resetGuid = expiryTime.ToString("ddMMyyyyHHmmssFFFF");
                member.SetValue("resetGUID", resetGuid);
                Services.MemberService.Save(member);

                // Send the member an email with a Password Reset GUID in it.
                //var emailFrom = "bruce@syncrony.com";
                //var emailHelper = new EmailHelper();
                //emailHelper.SendResetPasswordEmail(member.Email, emailFrom, resetGuid);
            }
            else
            {
                ModelState.AddModelError("", $"We could not find a customer account matching {model.EmailAddress}");
                return CurrentUmbracoPage();
            }

            return RedirectToCurrentUmbracoPage();
        }

        [HttpGet]
        [ActionName("RenderResetPassword")]
        public ActionResult RenderResetPassword()
        {
            return PartialView("LLForms/_resetPassword", new ResetPasswordViewModel());
        }

        [HttpPost]
        [ActionName("HandleResetPassword")]
        [ValidateAntiForgeryToken]
        public ActionResult HandleResetPassword(ResetPasswordViewModel model)
        {
            if (!ModelState.IsValid)
                return CurrentUmbracoPage();

            // Find the member with the matching email address.
            var member = Services.MemberService.GetByEmail(model.EmailAddress);
            if (member != null)
            {
                // Get the querystring GUID
                var resetQS = Request.QueryString["resetGUID"];
                if (!string.IsNullOrEmpty(resetQS))
                {
                    // See if the QS matches the value on the member property
                    if (member.GetValue<string>("resetGUID") == resetQS)
                    {
                        // Got a match, now check to see if the exiry window is valid.
                        DateTime currentTime = DateTime.Now;
                        DateTime expiryTime = DateTime.ParseExact(resetQS, "ddMMyyyyHHmmssFFFF", null);
                        if (currentTime.CompareTo(expiryTime) < 0)
                        {
                            // Not expired, so update user password and remove the reset guid.
                            member.RawPasswordValue = model.Password;
                            member.SetValue("resetGUID", string.Empty);
                            Services.MemberService.Save(member);
                            Redirect("/member-login");
                        }
                        else
                        {
                            //ERROR: Reset GUID has expired
                            ModelState.AddModelError("", "Password Reset GUID has expired");
                            return CurrentUmbracoPage();
                        }
                    }
                    else
                    {
                        // ERROR: QS does not match what is stored on member property
                        ModelState.AddModelError("", "Invalid Password Reset GUID");
                        return CurrentUmbracoPage();
                    }
                }
                else
                {
                    // ERROR: No QS present - Invalid resetGUID
                    ModelState.AddModelError("", "Invalid Password Reset GUID");
                    return CurrentUmbracoPage();
                }
            }

            return RedirectToCurrentUmbracoPage();
        }

        #endregion

        #region Helper Methods

        private string GetDisplayName(string firstName, string lastName)
        {
            return $"{firstName} {lastName}";
        }

        #endregion
    }
}

Umb.LL_VPR/Controllers/VPRFormSurfaceController.cs
using System.Web.Mvc;
using System.Collections.Generic;
using Umbraco.Web.Mvc;
using Umb.VPR.ViewModels;
using System;
using System.Linq;
using Umbraco.Web;
using Umbraco.Web.PublishedContentModels;
using Umb.VPR.Data;
using Umb.VPR.Service;
using Umbraco.Core.Models;
using Umb.VPR.Domain.Model;

namespace Umb.VPR.Controllers
{
    public class VPRFormSurfaceController : SurfaceController
    {
        #region Properties

        protected IUnitOfWork DataContext { get; set; }
        protected IVPRService VPRService { get; set; }

        #endregion

        #region Ctor

        public VPRFormSurfaceController(IUnitOfWork dataContext, IVPRService vprService)
        {
            DataContext = dataContext;
            VPRService = vprService;
        }

        #endregion

        #region Controller Methods

        [ChildActionOnly]
        [ActionName("RenderVPRForm")]
        public ActionResult RenderVPRForm(int nodeId)
        {
            // Check if "Customer" member is logged in.
            if (Members.IsLoggedIn() && Members.GetCurrentMember().DocumentTypeAlias == "Customer")
            {
                // Fetch Member
                var member = Members.GetCurrentMember();
                // Fetch all available event types.
                var eventTypes = Umbraco.TypedContentSingleAtXPath("//VPREventTypeFolder").Children();
                return PartialView("VPRForms/_vprForm", new VPRFormViewModel
                {
                    CurrentNodeId = nodeId,
                    MemberId = Members.GetCurrentMemberId(),
                    MonthId = DateTime.Now.Month,
                    Venues = Umbraco.TypedContentAtXPath("//companyFolder")
                        .FirstOrDefault()
                        .Children()
                        .Where(
                            x => x.GetPropertyValue<int>("associatedMember") == member.Id
                        ).ToList(),
                    Items = new List<EventItemViewModel> {
                        new EventItemViewModel {Id = 1, EventTypes = eventTypes }
                    }
                });
            }
            else {
                return Content(String.Format("<div class=\"spc alert alert-success alert-dismissible fade in\" role=\"alert\"><div class=\"info\">{0}</div></div>", "Member Access is Required"));
            }            
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult HandleVPRForm(VPRFormViewModel model)
        {
            if (!ModelState.IsValid)
            {
                TempData["IsSuccessful"] = false;
                return JavaScript(string.Format("$('#VPRError_{0}').show(); $('#VPRError_{0}').html('{1}');", model.CurrentNodeId, "General Error"));
            }

            var currentNode = Umbraco.TypedContent(model.CurrentNodeId);
            var member = Umbraco.TypedMember(model.MemberId);
            var venue = Umbraco.TypedContent(model.VenueId);
            if (member != null && venue != null)
            {
                var vprItem = new VPRItem
                {
                    MonthId = model.MonthId,
                    MemberId = model.MemberId,
                    MemberName = member.Name,
                    VenueId = venue.Id,
                    VenueName = venue.GetPropertyValue<string>("companyName"),
                    PostalCode = venue.GetPropertyValue<string>("postalCode"),
                    CreatedDate = DateTime.Now
                };

                foreach (var item in model.Items)
                {
                    vprItem.LineItems.Add(new VPRLineItem
                    {
                        HeaderId = vprItem.Id,
                        EventType = item.EventType,
                        TotalNoOfEvents = item.TotalNoOfEvents,
                        TotalNoOfDelegates = item.TotalNoOfDelegates,
                        AverageDDR = item.AverageDDR
                    });
                }

                // Save the captured data to DB.
                VPRService.CreateItem(vprItem);
                
                // Update success flag (in a TempData key)
                TempData["IsSuccessful"] = true;
                TempData["Message"] = currentNode.GetProperty("submissionMessage").Value.ToString();

                // Redirect to current page. (ensures form fields are cleared)
                return RedirectToCurrentUmbracoPage();
            }
            else
            {
                // TODO: Error Venue or Member is null.
                TempData["IsSuccessful"] = false;
                return JavaScript(string.Format("$('#VPRError_{0}').show(); $('#VPRError_{0}').html('{1}');", model.CurrentNodeId, "General Error"));
            }
        }


        [HttpPost]
        public ActionResult AddRow(int index)
        {
            // Fetch all available event types.
            IEnumerable<IPublishedContent> eventTypes = Umbraco.TypedContentSingleAtXPath("//VPREventTypeFolder")
                .Children();

            // Create and initialize the new line item.
            var newRow = new EventItemViewModel { Id = index, EventTypes = eventTypes };
            ViewData.TemplateInfo.HtmlFieldPrefix = string.Format("Items[{0}]", index);
            return PartialView("~/Views/Shared/EditorTemplates/EventItemViewModel.cshtml", newRow);
        }

        #endregion
    }
}

Umb.LL_VPR/Views/Partials/VPRForms/_forgotPassword.cshtml
@using Umbraco;
@using Umbraco.Web.Mvc;
@using Umb.VPR.ViewModels;
@using Umb.VPR.Controllers;
@inherits UmbracoViewPage<ForgotPasswordViewModel>
@{
    Html.EnableClientValidation(true);
    Html.EnableUnobtrusiveJavaScript(true);
}
@if (Convert.ToBoolean(TempData["IsSuccessful"]))
{
    <div class="alert alert-success">
        <h4>Forgot Password Email Notification</h4>
        <p>We have sent you an email with a password reset link which you can use to reset your password.</p>
    </div>
}
else
{
    using (Html.BeginUmbracoForm<AuthSurfaceController>("HandleForgotPassword", null, htmlAttributes: new { @class = "forgotten-password" }))
    {
        @Html.AntiForgeryToken()
        @Html.ValidationSummary()
        <fieldset>
            <div class="form-group">
                @Html.LabelFor(x => Model.EmailAddress, "Email address", new { @class = "control-label" })
                @Html.TextBoxFor(x => Model.EmailAddress, new { @class = "form-control", placeholder = "Email Address" })
                @Html.ValidationMessageFor(model => model.EmailAddress, string.Empty, new { @class = "help-block" })
            </div>
            <div class="form-group">
                <button type="submit" class="btn btn-primary">Remind me</button>
            </div>
        </fieldset>
    }
}

Umb.LL_VPR/Views/Partials/VPRForms/_login.cshtml
@using Umbraco.Web.Mvc;
@using Umb.VPR.ViewModels;
@using Umb.VPR.Controllers;
@inherits UmbracoViewPage<LoginViewModel>
@using (Html.BeginUmbracoForm<AuthSurfaceController>("HandleLogin"))
{
    var currentNode = Umbraco.TypedContent(UmbracoContext.PageId);
    if (TempData["LoginFailure"] != null)
    {
        <div class="alert alert-danger alert-dismissible fade in">
            <div class="info">
                <p>@TempData["LoginFailure"]</p>
            </div>
        </div>
    }

    @Html.AntiForgeryToken()
    <div class="login">
        @Html.HiddenFor(x => Model.ReturnUrl)
        <fieldset>
            <div class="form-group">
                @Html.LabelFor(x => Model.Username, htmlAttributes: new { @class = "control-label" })
                @Html.TextBoxFor(x => Model.Username, new { autocapitalize = "off", @class = "form-control" })
                @Html.ValidationMessageFor(x => Model.Username, umbraco.library.GetDictionaryItem("USN Form Username Validation"))
            </div>
            <div class="form-group">
                @Html.LabelFor(x => Model.Password, htmlAttributes: new { @class = "control-label" })
                @Html.PasswordFor(x => Model.Password, new { @class = "form-control" })
                @Html.ValidationMessageFor(x => Model.Password, umbraco.library.GetDictionaryItem("USN Form Password Validation"))
            </div>
        </fieldset>
        <fieldset>
            <button class="btn c1-bg c5-text" type="submit">
                <span>@currentNode.GetProperty("loginFormButtonText").Value</span>
            </button>

            <a href="/forgot-password" class="">Forgot Password</a>
        </fieldset>
    </div>
}

Umb.LL_VPR/Views/Partials/VPRForms/_resetPassword.cshtml
@using Umbraco.Web.Mvc;
@using Umb.VPR.ViewModels;
@using Umb.VPR.Controllers;
@inherits UmbracoViewPage<ResetPasswordViewModel>
@{
    Html.EnableClientValidation(true);
    Html.EnableUnobtrusiveJavaScript(true);
}

@if (!ViewData.ModelState.IsValid)
{
    <h3>Errors</h3>
    foreach (ModelState modelState in ViewData.ModelState.Values)
    {
        var errors = modelState.Errors;

        if (errors.Any())
        {
            <ul>
                @foreach (ModelError error in errors)
                {
                    <li><em>@error.ErrorMessage</em></li>
                }
            </ul>
        }
    }
}

@using (Html.BeginUmbracoForm<AuthSurfaceController>("HandleResetPassword", null, htmlAttributes: new { @class = "reset-password" }))
{
    var currentNode = Umbraco.TypedContent(UmbracoContext.PageId);
    @Html.AntiForgeryToken()
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Reset your Password</legend>
        <div class="form-group">
            @Html.LabelFor(x => Model.EmailAddress, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(x => Model.EmailAddress, new { @class = "form-control", placeholder = "Email Address" })
            @Html.ValidationMessageFor(x => Model.EmailAddress, string.Empty, new { @class = "help-block" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => Model.Password, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(x => Model.Password, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => Model.Password, string.Empty, new { @class = "help-block" })
        </div>
        <div class="form-group">
            @Html.LabelFor(x => Model.ConfirmPassword, htmlAttributes: new { @class = "control-label" })
            @Html.EditorFor(x => Model.ConfirmPassword, new { @class = "form-control" })
            @Html.ValidationMessageFor(x => Model.ConfirmPassword, string.Empty, new { @class = "help-block" })
        </div>
    </fieldset>
    <fieldset>
        <button class="btn c1-bg c5-text" type="submit">
            <span>Reset Password</span>
        </button>
    </fieldset>

}

Umb.LL_VPR/Views/Partials/VPRForms/_vprForm.cshtml
@using Umbraco.Web.Mvc;
@using Umb.VPR.ViewModels;
@using Umb.VPR.Controllers;
@using USN.Heading.Umbraco.Models;
@inherits UmbracoViewPage<VPRFormViewModel>
@{
    Html.EnableClientValidation(true);
    Html.EnableUnobtrusiveJavaScript(true);
    var containerId = "VPRFormContainer_" + Model.CurrentNodeId;
    var errorId = "VPRError_" + Model.CurrentNodeId;
    var successId = "VPRSuccess_" + Model.CurrentNodeId;
    var lineItemsId = "VPRLineItems_" + Model.CurrentNodeId;
    var ajaxLoadingId = "VPRAjax_" + Model.CurrentNodeId;
}
@if (!ViewData.ModelState.IsValid)
{

}

@using (Ajax.BeginForm("HandleVPRForm", "AuthSurface",
    new AjaxOptions
    {
        HttpMethod = "POST",
        InsertionMode = InsertionMode.Replace,
        UpdateTargetId = containerId,
        LoadingElementId = ajaxLoadingId
    },
    htmlAttributes: new { @class = "vpr-form", id ="vprForm" }))
{
    var currentNode = Umbraco.TypedContent(Model.CurrentNodeId);
    @Html.AntiForgeryToken()
    @Html.Hidden("CurrentNodeID", Model.CurrentNodeId)
    @Html.Hidden("MemberId", Model.MemberId)

    if (currentNode.Parent.Parent.IsDocumentType("USNHomepage") || currentNode.Parent.Parent.IsDocumentType("USNAdvancedPage"))
    {
        if (currentNode.HasValue("width") && currentNode.GetProperty("width").Value.ToString() == "Centered")
        {
            @Html.Raw("<div id=\"mid-col\" class=\"col-md-8 col-md-offset-2 col-sm-10 col-sm-offset-1 col-xs-12\"><div class=\"spc forms\">")
        }
        else
        {
            @Html.Raw("<div id=\"wide-col\" class=\"col-xs-12\"><div class=\"spc forms\">")
        }
    }

    <div class="vpr form">
        <div class="inner c5-bg has-borders c6-borders">
            @if (currentNode.HasValue("VPR_Heading"))
            {
                var vprHeading = currentNode.GetPropertyValue<USNHeading>("VPR_Heading");
                if (vprHeading != null && !String.IsNullOrEmpty(vprHeading.Heading))
                {
                    @Html.Raw("<" + vprHeading.HeadingStyle + " class=\"heading main\">")
                    @vprHeading.Heading
                    @Html.Raw("</" + vprHeading.HeadingStyle + ">")
                }
            }
            @if (currentNode.HasValue("VPR_Introduction"))
            {
                @Html.Raw(currentNode.GetProperty("VPR_Introduction").Value)
            }
                        
            <div id="@containerId">
                <div id="@errorId" class="alert alert-danger alert-dismissible fade in" style="display:none"></div>
                <div id="@successId" class="alert alert-success alert-dismissible fade in" style="display:none;"></div>  
                <fieldset>
                    <div class="form-group">
                        <div class="row">
                            <div class="col-md-6 col-xs-12">
                                @Html.LabelFor(m => Model.MonthId, htmlAttributes: new { @class = "control-label" })
                                @Html.DropDownListFor(m => Model.MonthId, Model.Months, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.MonthId, string.Empty, new { @class = "help-block" })
                            </div>
                            <div class="col-md-6 col-xs-12">
                                @Html.LabelFor(m => Model.VenueId, htmlAttributes: new { @class = "control-label" })
                                @Html.DropDownListFor(m => Model.VenueId, Model.VenueItems, htmlAttributes: new { @class = "form-control" })
                                @Html.ValidationMessageFor(x => Model.VenueId, string.Empty, new { @class = "help-block" })
                            </div>
                        </div>
                    </div>
                </fieldset>
                <fieldset id="@lineItemsId">
                    <legend class="text-muted">Enter your monthly performance data</legend>
                    <div class="row">
                        <div class="col-md-5 col-xs-12">
                            @Html.Label("Event Type")
                        </div>
                        <div class="col-md-2 col-xs-12">
                            @Html.Label("Total No Of Events")
                        </div>
                        <div class="col-md-2 col-xs-12">
                            @Html.Label("Total No Of Delegates")
                        </div>
                        <div class="col-md-2 col-xs-12">
                            @Html.Label("Average DDR")
                        </div>
                        <div class="col-xs-1">
                            @*Empty Column*@
                        </div>
                    </div>
                    @for (var i = 0; i < Model.Items.Count(); i++)
                    {
                        @Html.EditorFor(m => Model.Items[i])
                    }
                </fieldset>
                <fieldset class="buttons">
                    <button class="btn c1-bg c5-text" type="submit">
                        <span>Submit Data</span>
                    </button>
                    <a id="addNewRow" class="btn btn-default">
                        <span>Add New Row</span>
                    </a>
                </fieldset>
                <div class="ajax-loading" id="@ajaxLoadingId" style="display:none">
                    <div class="loading">
                        <span class="message">Sending ...</span>
                    </div>
                </div>
            </div>
            <div id="@ajaxLoadingId" style="display:none">
                <img src="~/images/icons/loading-on-white.gif" style="height:60px;width:60px" />
            </div>
        </div>
    </div>

    if (currentNode.Parent.Parent.IsDocumentType("USNHomepage") || currentNode.Parent.Parent.IsDocumentType("USNAdvancedPage"))
    {
        @Html.Raw("</div></div>")
    }
}

<script type="text/javascript">
    (function ($) {
        $.validator.unobtrusive.parseDynamicContent = function (selector) {
            // use the normal unobstrusive.parse method
            $.validator.unobtrusive.parse(selector);

            // get the relevant form
            var form = $(selector).first().closest('form');

            //get the collections of unobstrusive validators, and jquery validators and compare the two.
            var unobtrusiveValidation = form.data('unobtrusiveValidation');
            var validator = form.validate();
            $.each(unobtrusiveValidation.options.rules, function (elname, elrules) {
                if (validator.settings.rules[elname] == undefined) {
                    var args = {};
                    $.extend(args, elrules);
                    args.messages = unobtrusiveValidation.options.messages[elname];
                    //edit:use quoted strings for the name selector
                    $("[name='" + elname + "']").rules("add", args);
                } else {
                    $.each(elrules, function (rulename, data) {
                        if (validator.settings.rules[elname][rulename] == undefined) {
                            var args = {};
                            args[rulename] = data;
                            args.messages = unobtrusiveValidation.options.messages[elname][rulename];
                            //edit:use quoted strings for the name selector
                            $("[name='" + elname + "']").rules("add", args);
                        }
                    });
                }
            });
        }
    })($);
    $(document).on("sumbit", "#vprForm", function () {
        alert('submitted');
    });
    $(document).on("click", "#addNewRow", function () {
        var nextIndex = $("#@lineItemsId .form-group").length;
        $.ajax({
            url: '@this.Url.Action("AddRow", "VPRFormSurface")',
            type: 'POST',
            data: { index: nextIndex },
            success: function (results) {
                $("#@lineItemsId").append(results);
                $.validator.unobtrusive.parseDynamicContent('#@lineItemsId .form-group:last');
            }
        });
        return false;
    });

    $(document).on("click", ".removeButton", function () {
        // Get item row to delete.
        var itemToDelete = $(this).closest('.form-group');
        // TODO: remove validation.

        // Mark row as deleted.
        $(this).prev("input").val('true');
        // Hide row.
        itemToDelete.hide();
        
        return false;
    });
</script>